name: Unity Compile Tools

on:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
    android-player:
        name: AndroidPlayer
        runs-on: "ubuntu-latest"
        env:
          VERSION: "6000.0.40f1"
          CHANGESET: "157d81624ddf"
        steps:
          - uses: actions/cache@v5
            with:
                path: |
                  Unity-android.tar.xz
                key: Unity-${{ env.VERSION }}-${{ env.CHANGESET }}-android-player
          - name: Get AndroidPlayer
            run: |
              # Get Android Specific
              if [ ! -f Unity-android.tar.xz ]; then
                curl "https://download.unity3d.com/download_unity/$CHANGESET/MacEditorTargetInstaller/UnitySetup-Android-Support-for-Editor-$VERSION.pkg" -o Unity-android.tar.xz
              fi
              7z x Unity-android.tar.xz
              
              mkdir Android
              mkdir AndroidPlayer
              mkdir AndroidPlayer/StaticLibs
              cd Android
              
              7z x ../Payload~
              rm -rf ../Payload~
              
              cp -r Variations/il2cpp/Managed ../AndroidPlayer/Managed
              cp Tools/AndroidNativeLink.xml ../AndroidPlayer/AndroidNativeLink.xml
              cp modules.asset ../AndroidPlayer/modules.asset
              
              cp Variations/il2cpp/Release/StaticLibs/arm64-v8a/baselib.a ../AndroidPlayer/StaticLibs/baselib.a
              cp Variations/il2cpp/Release/StaticLibs/arm64-v8a/compile.rsp ../AndroidPlayer/StaticLibs/compile.rsp
              cp Variations/il2cpp/Release/StaticLibs/arm64-v8a/link.rsp ../AndroidPlayer/StaticLibs/link.rsp
              cp Variations/il2cpp/Release/Libs/arm64-v8a/libunity.so ../AndroidPlayer/libunity.so
              cd ..

              tar cvf - AndroidPlayer | gzip -9 - > androidplayer.tar.gz
          - uses: actions/upload-artifact@v7
            with:
              archive: false
              name: androidplayer
              path: androidplayer.tar.gz
    mac:
        name: MacOS
        runs-on: "ubuntu-latest"
        env:
          VERSION: "6000.0.40f1"
          CHANGESET: "157d81624ddf"
        steps:
          - uses: actions/cache@v5
            with:
                path: |
                  Unity.tar.xz
                key: Unity-${{ env.VERSION }}-${{ env.CHANGESET }}-mac-os
          - name: Get UnityData for OSX
            run: |
              if [ ! -f Unity.tar.xz ]; then
                curl "https://download.unity3d.com/download_unity/$CHANGESET/MacEditorInstallerArm64/Unity-$VERSION.pkg" -o Unity.tar.xz
              fi
              
              echo "Making UnityData"
              mkdir UnityData
              7z x Unity.tar.xz
              7z x Payload~ -o./ ./Unity/Unity.app/Contents/MonoBleedingEdge/lib/mono/unityaot-linux ./Unity/Unity.app/Contents/il2cpp
              rm -rf Payload~
              
              cp -r Unity/Unity.app/Contents/MonoBleedingEdge/lib/mono/unityaot-linux UnityData
              cp -r Unity/Unity.app/Contents/il2cpp UnityData
              rm -rf Unity

              tar cvf - UnityData | gzip -9 - > unitydata-osx.tar.gz
          - uses: actions/upload-artifact@v7
            with:
              archive: false
              name: unitydata-osx
              path: unitydata-osx.tar.gz
    linux:
        name: Linux
        runs-on: "ubuntu-latest"
        env:
          VERSION: "6000.0.40f1"
          CHANGESET: "157d81624ddf"
        steps:
          - uses: actions/cache@v5
            with:
                path: |
                  Unity.tar.xz
                key: Unity-${{ env.VERSION }}-${{ env.CHANGESET }}-linux
          - name: Download Unity Editor
            run: |
              if [ ! -f Unity.tar.xz ]; then
                curl "https://download.unity3d.com/download_unity/$CHANGESET/LinuxEditorInstaller/Unity-$VERSION.tar.xz" -o Unity.tar.xz
              fi
              
              tar -xf Unity.tar.xz
              echo "Making UnityData"
              mkdir UnityData
              cp -r Editor/Data/MonoBleedingEdge/lib/mono/unityaot-linux UnityData
              cp -r Editor/Data/il2cpp UnityData
              rm -rf Editor
              tar cvf - UnityData | gzip -9 - > unitydata-linux.tar.gz
          - uses: actions/upload-artifact@v7
            with:
              archive: false
              name: unitydata-linux
              path: unitydata-linux.tar.gz
    windows:
        name: Windows
        runs-on: "ubuntu-latest"
        env:
          VERSION: "6000.0.40f1"
          DIGEST: "sha256:c62d20e92f609345d0ff4871e42fc1fedc6e76f7dfe61eddcb8cbfa67dc24a8c"
        steps:
          - uses: actions/cache@v5
            with:
                path: |
                  Unity.tar.gz
                key: Unity-${{ env.DIGEST }}-windows
          - name: Download Unity Editor
            run: |
              if [ ! -f Unity.tar.gz ]; then
                curl -so "token.json" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:unityci/editor:pull";
                token=$(cat token.json | jq -jr ".token")
                curl -L -o Unity.tar.gz -H "Authorization: Bearer ${token}" "https://registry-1.docker.io/v2/unityci/editor/blobs/$DIGEST"
              fi
              
              tar -zxvf Unity.tar.gz
              echo "Making UnityData"
              chmod -R 755 ./Files
              chmod -R 755 ./Hives
              mkdir UnityData
              cp -r "./Files/UnityEditor/$VERSION/Data/MonoBleedingEdge/lib/mono/unityaot-linux" UnityData
              cp -r "./Files/UnityEditor/$VERSION/Data/il2cpp" UnityData
              
              tar cvf - UnityData | gzip -9 - > unitydata-windows.tar.gz
          - uses: actions/upload-artifact@v7
            with:
              archive: false
              name: unitydata-windows
              path: unitydata-windows.tar.gz